/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'sans-serif'],
      },
      boxShadow: {
        'capsule': '0 4px 16px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)',
        'card-hover': '0 8px 24px rgba(0,0,0,0.08)',
        'ambient': '0 20px 50px rgba(43, 90, 232, 0.04), 0 4px 12px rgba(0, 0, 0, 0.02)',
        'float': '0 8px 32px rgba(43, 90, 232, 0.06), 0 2px 8px rgba(0, 0, 0, 0.03)',
        'ct-card': '0 4px 24px rgba(79, 70, 229, 0.08)',
        'ct-card-hover': '0 8px 40px rgba(79, 70, 229, 0.15)',
        'ct-glow': '0 0 60px rgba(79, 70, 229, 0.15)',
      },
      colors: {
        brand: {
          DEFAULT: '#1D51DF',
          light: '#4670FE',
          dark: '#0043D1',
          50: '#EEF2FE',
          100: '#D9E2FD',
          500: '#1D51DF',
          600: '#0043D1',
        },
        ds: {
          surface: '#FCF8FB',
          'surface-dim': '#DCD9DF',
          'surface-bright': '#FCF8FB',
          'surface-container': '#F0EDF1',
          'surface-container-low': '#F6F2F6',
          'surface-container-high': '#EAE7EC',
          'surface-container-highest': '#E5E1E7',
          'surface-container-lowest': '#FFFFFF',
          'on-surface': '#333236',
          'on-surface-variant': '#605E63',
          'on-background': '#333236',
          primary: '#1D51DF',
          'primary-container': '#4670FE',
          'on-primary': '#FAF8FF',
          secondary: '#5A5E72',
          'secondary-container': '#DEE1F9',
          tertiary: '#6E567D',
          'tertiary-container': '#EBCCFB',
          outline: '#7C7A7F',
          'outline-variant': '#B3B1B7',
          'inverse-surface': '#0E0E10',
          'inverse-on-surface': '#9F9C9F',
          'inverse-primary': '#6989FF',
        },
        apple: {
          text: '#333236',
          'text-secondary': '#605E63',
          'text-tertiary': '#7C7A7F',
          border: '#B3B1B7',
          'border-light': 'rgba(179, 177, 183, 0.2)',
          bg: '#FCF8FB',
          'bg-secondary': '#F6F2F6',
          'bg-tertiary': '#F0EDF1',
        },
        ct: {
          primary: '#4F46E5',
          secondary: '#7C3AED',
          bg: '#F8FAFC',
          surface: '#FFFFFF',
          text: '#0F172A',
          'text-secondary': '#475569',
          'text-muted': '#94A3B8',
          border: '#E2E8F0',
          accent: '#06B6D4',
        },
      },
      borderRadius: {
        'ds': '8px',
        'ds-lg': '12px',
        'ds-xl': '16px',
        'ds-2xl': '24px',
      },
      animation: {
        'ct-float': 'ctFloat 6s ease-in-out infinite',
        'ct-fade-up': 'ctFadeUp 0.6s ease-out both',
      },
      keyframes: {
        ctFloat: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        ctFadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
